package sysdemo;

import Utils.ServiceManager;
import android.os.Bundle;
import android.graphics.Bitmap;
import com.dreamtek.smartpos.system_service.aidl.*;
import com.dreamtek.smartpos.system_service.aidl.settings.*;

/** Direct calls compiled against the pinned unified AAR; no reflected Binder dispatch. */
final class SystemContractCalls {
    static Object invoke(ServiceManager.Snapshot session, String key, Object[] args) throws Exception {
        switch (key) {
            case "ISystemManager.installApp": session.system.installApp((String) args[0], (IAppInstallObserver) args[1], (String) args[2]); return null;
            case "ISystemManager.uninstallApp": session.system.uninstallApp((String) args[0], (IAppDeleteObserver) args[1]); return null;
            case "ISystemManager.reboot": session.system.reboot(); return null;
            case "ISystemManager.isMaskHomeKey": session.system.isMaskHomeKey((Boolean) args[0]); return null;
            case "ISystemManager.isMaskRecentStatusKey": session.system.isMaskRecentStatusKey((Boolean) args[0]); return null;
            case "ISystemManager.isMaskStatusBard": session.system.isMaskStatusBard((Boolean) args[0]); return null;
            case "ISystemManager.chekcK21Update": return session.system.chekcK21Update((String) args[0], (String) args[1]);
            case "ISystemManager.updateROM": session.system.updateROM((String) args[0]); return null;
            case "ISystemManager.getNetworkManager": return session.system.getNetworkManager();
            case "ISystemManager.setLocationMode": session.system.setLocationMode((Integer) args[0]); return null;
            case "ISystemManager.isAdbMode": return session.system.isAdbMode();
            case "ISystemManager.killApplication": return session.system.killApplication((String) args[0]);
            case "ISystemManager.restartApplication": return session.system.restartApplication((String) args[0]);
            case "ISystemManager.initLogcat": session.system.initLogcat((Integer) args[0], (Integer) args[1], (Bundle) args[2]); return null;
            case "ISystemManager.getLogcat": return session.system.getLogcat((String) args[0], (Integer) args[1]);
            case "ISystemManager.getLaunchAppsInfo": return session.system.getLaunchAppsInfo((Long) args[0], (Long) args[1]);
            case "ISystemManager.getSettingsManager": return session.system.getSettingsManager();
            case "ISystemManager.takeCapture": return session.system.takeCapture();
            case "ISystemManager.shutdownDevice": session.system.shutdownDevice(); return null;
            case "ISystemManager.UpdateSecurityDriver": return session.system.UpdateSecurityDriver((String) args[0]);
            case "ISystemManager.isAppForeground": return session.system.isAppForeground((String) args[0]);
            case "ISystemManager.getScreenBrightness": return session.system.getScreenBrightness();
            case "ISystemManager.changeScreenBrightness": session.system.changeScreenBrightness((Integer) args[0]); return null;
            case "ISystemManager.verifySignSync": return session.system.verifySignSync((String) args[0]);
            case "ISystemManager.verifySign": session.system.verifySign((String) args[0], (IVerifysignCallback) args[1]); return null;
            case "ISystemManager.getSysDeviceInfo": return session.system.getSysDeviceInfo();
            case "ISysDeviceInfo.getSerialNo": return session.deviceInfo.getSerialNo();
            case "ISysDeviceInfo.getIMSI": return session.deviceInfo.getIMSI();
            case "ISysDeviceInfo.getIMEI": return session.deviceInfo.getIMEI();
            case "ISysDeviceInfo.getICCID": return session.deviceInfo.getICCID();
            case "ISysDeviceInfo.getManufacture": return session.deviceInfo.getManufacture();
            case "ISysDeviceInfo.getModel": return session.deviceInfo.getModel();
            case "ISysDeviceInfo.getAndroidOSVersion": return session.deviceInfo.getAndroidOSVersion();
            case "ISysDeviceInfo.getAndroidKernelVersion": return session.deviceInfo.getAndroidKernelVersion();
            case "ISysDeviceInfo.getROMVersion": return session.deviceInfo.getROMVersion();
            case "ISysDeviceInfo.getFirmwareVersion": return session.deviceInfo.getFirmwareVersion();
            case "ISysDeviceInfo.getHardwareVersion": return session.deviceInfo.getHardwareVersion();
            case "ISysDeviceInfo.getTUSN": return session.deviceInfo.getTUSN((Integer) args[0], (byte[]) args[1]);
            case "ISysDeviceInfo.getPN": return session.deviceInfo.getPN();
            case "ISysDeviceInfo.setPowerStatus": session.deviceInfo.setPowerStatus((Boolean) args[0]); return null;
            case "ISysDeviceInfo.getRamTotal": return session.deviceInfo.getRamTotal();
            case "ISysDeviceInfo.getRamAvailable": return session.deviceInfo.getRamAvailable();
            case "ISysDeviceInfo.getRomTotal": return session.deviceInfo.getRomTotal();
            case "ISysDeviceInfo.getRomAvailable": return session.deviceInfo.getRomAvailable();
            case "ISysDeviceInfo.getMobileDataUsageTotal": return session.deviceInfo.getMobileDataUsageTotal();
            case "ISysDeviceInfo.getBootCounts": return session.deviceInfo.getBootCounts();
            case "ISysDeviceInfo.getPrintPaperLen": return session.deviceInfo.getPrintPaperLen();
            case "ISysDeviceInfo.getMagCardUsedTimes": return session.deviceInfo.getMagCardUsedTimes();
            case "ISysDeviceInfo.getSmartCardUsedTimes": return session.deviceInfo.getSmartCardUsedTimes();
            case "ISysDeviceInfo.getCTLSCardUsedTimes": return session.deviceInfo.getCTLSCardUsedTimes();
            case "ISysDeviceInfo.getBatteryTemperature": return session.deviceInfo.getBatteryTemperature();
            case "ISysDeviceInfo.getBatteryLevel": return session.deviceInfo.getBatteryLevel();
            case "ISysDeviceInfo.getMEID": return session.deviceInfo.getMEID();
            case "ISysDeviceInfo.getTamperCode": return session.deviceInfo.getTamperCode();
            case "ISysDeviceInfo.getServiceVersion": return session.deviceInfo.getServiceVersion();
            case "ISysDeviceInfo.getCertificate": return session.deviceInfo.getCertificate((Integer) args[0]);
            case "ISysDeviceInfo.getBatteryChargingTimes": return session.deviceInfo.getBatteryChargingTimes();
            case "ISysDeviceInfo.getDeviceStatus": return session.deviceInfo.getDeviceStatus((Bundle) args[0]);
            case "ISysDeviceInfo.getButtonBatteryVol": return session.deviceInfo.getButtonBatteryVol();
            case "ISysDeviceInfo.getDeviceInfo": return session.deviceInfo.getDeviceInfo();
            case "ISysDeviceInfo.getDeviceInfoEx": return session.deviceInfo.getDeviceInfoEx((Bundle) args[0]);
            case "INetworkManager.setNetworkType": session.network.setNetworkType((Integer) args[0]); return null;
            case "INetworkManager.getNetworkType": return session.network.getNetworkType();
            case "INetworkManager.enableWifi": session.network.enableWifi((Boolean) args[0]); return null;
            case "INetworkManager.enableAirplayMode": session.network.enableAirplayMode((Boolean) args[0]); return null;
            case "INetworkManager.setAPN": return session.network.setAPN((Bundle) args[0]);
            case "INetworkManager.enableMobileData": session.network.enableMobileData((Boolean) args[0]); return null;
            case "INetworkManager.getSelectedApnInfo": return session.network.getSelectedApnInfo();
            case "INetworkManager.selectMobileDataOnSlot": return session.network.selectMobileDataOnSlot((Integer) args[0]);
            case "INetworkManager.isMultiNetwork": return session.network.isMultiNetwork();
            case "INetworkManager.setMultiNetwork": session.network.setMultiNetwork((Boolean) args[0]); return null;
            case "INetworkManager.getMultiNetworkPrefer": return session.network.getMultiNetworkPrefer();
            case "INetworkManager.setMultiNetworkPrefer": return session.network.setMultiNetworkPrefer((String) args[0]);
            case "INetworkManager.setEthernetStaticIp": session.network.setEthernetStaticIp((Bundle) args[0]); return null;
            case "INetworkManager.setWifiStaticIp": session.network.setWifiStaticIp((Bundle) args[0]); return null;
            case "INetworkManager.setMobilePreferredNetworkType": session.network.setMobilePreferredNetworkType((String) args[0]); return null;
            case "INetworkManager.getMobilePreferredNetworkType": return session.network.getMobilePreferredNetworkType();
            case "INetworkManager.deleteAPN": return session.network.deleteAPN((String) args[0]);
            case "INetworkManager.setDataRoamingEnabled": return session.network.setDataRoamingEnabled((Boolean) args[0], (Integer) args[1]);
            case "INetworkManager.addNetwork": return session.network.addNetwork((Bundle) args[0]);
            case "INetworkManager.connectWifi": return session.network.connectWifi((String) args[0]);
            case "INetworkManager.addNetworkAllowedList": session.network.addNetworkAllowedList((String) args[0], (IAddNetworkAllowedListObserver) args[1], (Boolean) args[2]); return null;
            case "INetworkManager.setProxy": return session.network.setProxy((String) args[0], (Bundle) args[1]);
            case "INetworkManager.getMacAddress": return session.network.getMacAddress((Integer) args[0]);
            case "INetworkManager.getWifiProxyState": return session.network.getWifiProxyState();
            case "INetworkManager.setWifiProxyState": session.network.setWifiProxyState((Boolean) args[0]); return null;
            case "INetworkManager.getCurrentNetworkDetails": return session.network.getCurrentNetworkDetails();
            case "ISettingsManager.settingsSetActions": return session.settings.settingsSetActions((Integer) args[0], (Bundle) args[1]);
            case "ISettingsManager.settingsReadActions": return session.settings.settingsReadActions((Integer) args[0], (Bundle) args[1]);
            case "ISettingsManager.settingPCIRebootTime": return session.settings.settingPCIRebootTime((Integer) args[0], (Integer) args[1], (Integer) args[2]);
            case "ISettingsManager.getPCIRebootTime": return session.settings.getPCIRebootTime();
            case "ISettingsManager.setScreenLock": session.settings.setScreenLock((Boolean) args[0]); return null;
            case "ISettingsManager.setDeviceBrightnessLevel": return session.settings.setDeviceBrightnessLevel((Integer) args[0]);
            case "ISettingsManager.isShowBatteryPercent": return session.settings.isShowBatteryPercent((Boolean) args[0]);
            case "ISettingsManager.enableAlertWindow": session.settings.enableAlertWindow((String) args[0]); return null;
            case "ISettingsManager.clearCachesByPackageName": session.settings.clearCachesByPackageName((String) args[0]); return null;
            case "ISettingsManager.setDefaultSystemLanguage": session.settings.setDefaultSystemLanguage((String) args[0], (String) args[1]); return null;
            case "ISettingsManager.setTimeZone": session.settings.setTimeZone((String) args[0]); return null;
            case "ISettingsManager.loadCertificate": return session.settings.loadCertificate((String) args[0]);
            case "ISettingsManager.setSettingPwd": return session.settings.setSettingPwd((String) args[0]);
            case "ISettingsManager.setWallpaper": return session.settings.setWallpaper((Bitmap) args[0]);
            case "ISettingsManager.isScreenLock": return session.settings.isScreenLock();
            case "ISettingsManager.setSleepDuration": session.settings.setSleepDuration((Integer) args[0]); return null;
            case "ISettingsManager.getSleepDuration": return session.settings.getSleepDuration();
            case "ISettingsManager.upgradeCustomPackages": session.settings.upgradeCustomPackages((String) args[0], (ICustomerConfigurationUpdateListener) args[1]); return null;
            case "ISettingsManager.setScreenSleep": session.settings.setScreenSleep(); return null;
            default: throw new IllegalArgumentException("Unknown system case: " + key);
        }
    }
}
